

name: build
on: [ workflow_dispatch ]
#on:
#  pull_request:
#    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - name: Run package creation
        run: |
          echo ${{ github.ref_name }}
          python -m pip install --user --upgrade build
          python -m build
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: kronoterm-cloud-api-${{ github.ref_name }}
          path: dist
      - name: Create a Release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: true


