name: build
on: [ workflow_dispatch ]
#on:
#  pull_request:
#    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - name: Archive package
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: github-actions-dev-${{ github.ref_name }}
          path: dist

      - name: Output artifact ID
        run: |
          echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
          echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs }}'

#      - name: Create a Release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ github.ref_name }}
#        run: |
#          gh release create "$tag" \
#              --repo="$GITHUB_REPOSITORY" \
#              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
#              --generate-notes
          

#        uses: comnoco/create-release-action@v2.0.5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          release_name: ${{ github.ref }}
#          tag_name: ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - First Change
#            - Second Change
#          draft: false
#          prerelease: false


